apiVersion: apps/v1
kind: Deployment
metadata:
  name: bento-new
  namespace: bento-logging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: lgbm-model-init
          image: zerooneai/lgbm_classifier:0.0.3
          ports:
            - containerPort: 3000
              protocol: TCP
        - name: fluent-bit
          image: fluent/fluent-bit:1.5
          imagePullPolicy: Always
          ports:
            - containerPort: 2020
          env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch"
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: fluent-bit-config
            mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
#      serviceAccountName: fluent-bit
#      tolerations:
#      - key: node-role.kubernetes.io/master
#        operator: Exists
#        effect: NoSchedule
#      - operator: "Exists"
#        effect: "NoExecute"
#      - operator: "Exists"
#        effect: "NoSchedule"
