apiVersion: v1
kind: Service
metadata:
  name: model-lb
  namespace: bento-logging
spec:
  type: LoadBalancer
  ports:
    - port: 3000
#      targetPort: 31000
      protocol: TCP
  selector:
    app: model
